### ISSUE TITLE
Unclear. Are linux deamons supported?

### ISSUE THREAD

**Issue by DominicD** [Devolutions/ceviche-rs#21]
Hi I am a bit confused as your readme states this supports service and deamon. However your docs says:
"At the moment only Windows services are supported. The Service macro is inspired from the winservice crate."

So is deamon support still in development or what? 
Thanks

**Comment by awakecoding** [comment]
I agree the documentation and samples need a serious update. We have since added support for Windows, macOS and Linux. What is most lacking is a good cross-platform service sample with instructions on how to register it with each platform-specific service system. However, the code is definitely there, we have been using it to build services for all three platforms in our products. Take a look at the code, you'll see the support is there.

**Comment by DominicD** [comment]
Hey wow that was quite a fast answer 👍 
Ok I will test and report back if I have any problems

**Comment by thenextman** [comment]
Just to be clear; Linux support is based on systemd. We'll leave the issue open until we update the documentation. In the meantime don't hesitate to ask questions or open issues for any problems.
